import AnimeListKira from "./AnimeListKira";
import CarouselMobile from "./CarouselMobile";

const RandomPage = () => {
    const animeList = [
        {
            id: 1,
            name: "BanG Dream! It's MyGO!!!!!",
            portraitImage: 'https://cdn.myanimelist.net/images/anime/1891/136948l.jpg',
            landscapeImage: 'https://cs1.animestore.docomo.ne.jp/anime_kv/img/26/42/3/26423_1_9_8b.png?1685064649048',
            synopsis: "In their last year of middle school, the five band members of CRYCHIC went their separate ways after an unpleasant disbandment. Each wrestling with their own regrets, the girls enrolled in different high schools, hoping never to hear from one another again. Meanwhile, Anon Chihaya transfers to Haneoka Girls' Academy in the middle of the school year. As most students play in a band as a hobby, Anon desires to fit in and spends her first days trying to recruit members for her own band, envisioning herself as the group's vocalist. She befriends Tomori Takamatsu, a shy girl who seems interested but hesitant about joining. As it turns out, Tomori used to be part of CRYCHIC, an experience that has scarred her deeply. Through Tomori, Anon meets Taki Shiina and Soyo Nagasaki, both former members of the same band. Although Taki detests the idea of playing with Anon, Soyo is delighted to help her out. Now with Soyo by her side, Anon's dream of forming a band is within reach—if only she could find a few more members.",
            link: "/anime/54959",
        },
        {
            id: 2,
            name: 'Sword Art Online: Alicization',
            portraitImage: 'https://cdn.myanimelist.net/images/anime/1993/93837l.jpg',
            landscapeImage: 'https://a.storyblok.com/f/178900/1127x634/720330ad1f/f46ec80b578890984488e844b207f0761596807350_main.png/m/filters:quality(95)format(webp)',
            synopsis: "The Soul Translator is a state-of-the-art full-dive interface which interacts with the user's Fluctlight—the technological equivalent of a human soul—and fundamentally differs from the orthodox method of sending signals to the brain. The private institute Rath aims to perfect their creation by enlisting the aid of Sword Art Online survivor Kazuto Kirigaya. He works there as a part-time employee to test the system's capabilities in the Underworld: the fantastical realm generated by the Soul Translator. As per the confidentiality contract, any memories created by the machine in the virtual world are wiped upon returning to the real world. Kazuto can only vaguely recall a single name, Alice, which provokes a sense of unease when mentioned in reality. When Kazuto escorts Asuna Yuuki home one evening, they chance upon a familiar foe. Kazuto is mortally wounded in the ensuing fight and loses consciousness. When he comes to, he discovers that he has made a full-dive into the Underworld with seemingly no way to escape. He sets off on a quest, seeking a way back to the physical world",
            link: "/anime/36474",
        },
        {
            id: 3,
            name: 'Otome Game Sekai wa Mob ni Kibishii Sekai desu',
            portraitImage: 'https://cdn.myanimelist.net/images/anime/1161/121462l.jpg',
            landscapeImage: 'https://www.crunchyroll.com/imgsrv/display/thumbnail/1200x675/catalog/crunchyroll/10c91fb27baa9162df89dbbfa43a7f7e.jpe',
            synopsis: 'Blackmailed into playing a dating simulator set in a matriarchy, an ordinary man must put up with the unbearable and convoluted world until he clears the game. After countless days of grinding, he finally manages to beat it, but his hardcore gaming comes at a cost: extreme sleep deprivation and hunger. While heading out to the convenience store to solve one of these problems, the man tumbles down the stairs and falls unconscious, only to wake up to the worst possible realization—he has been reincarnated into the game as the mob character Leon Fou Bartfort. Now trapped in a world he despises, Leon must use his knowledge of the game to navigate through the plot safely and sustain himself in a society where the odds are heavily stacked against him.',
            link: "/anime/50461"
        },

        {
            id: 4,
            name: 'Fruits Basket 1st Season',
            portraitImage: 'https://cdn.myanimelist.net/images/anime/1447/99827l.jpg',
            landscapeImage: 'https://a.storyblok.com/f/178900/640x360/08d5f36cff/df4c85bc3ba64872a8e967d0d75d0e3a1559257327_full.png/m/1200x675',
            synopsis: 'Tooru Honda has always been fascinated by the story of the Chinese zodiac that her beloved mother told her as a child. However, a sudden family tragedy changes her life, and subsequent circumstances leave her all alone. Tooru is now forced to live in a tent, but little does she know that her temporary home resides on the private property of the esteemed Souma family. Stumbling upon their home one day, she encounters Shigure, an older Souma cousin, and Yuki, the "prince" of her school. Tooru explains that she lives nearby, but the Soumas eventually discover her well-kept secret of being homeless when they see her walking back to her tent one night. Things start to look up for Tooru as they kindly offer to take her in after hearing about her situation. But soon after, she is caught up in a fight between Yuki and his hot-tempered cousin, Kyou. While trying to stop them, she learns that the Souma family has a well-kept secret of their own: whenever they are hugged by a member of the opposite sex, they transform into the animals of the Chinese zodiac. With this new revelation, Tooru will find that living with the Soumas is an unexpected adventure filled with laughter and romance.',
            link: "/anime/38680"
        },

        {
            id: 5,
            name: 'Kage no Jitsuryokusha ni Naritakute!',
            portraitImage: 'https://cdn.myanimelist.net/images/anime/1874/121869l.jpg',
            landscapeImage: 'https://a.storyblok.com/f/178900/836x470/26129818b4/4802bd7a599f52c2df66ab505ce23b231663153760_main.jpg/m/filters:quality(95)format(webp)',
            synopsis: `For as long as he can remember, Minoru Kagenou has been fixated on becoming as strong as possible, which has led him to undertake all kinds of rigorous training. This wish, however, does not stem from a desire to be recognized by others; rather, Minoru does everything he can to blend in with the crowd. So, while pretending to be a completely average student during the day, he arms himself with a crowbar and ruthlessly thrashes local biker gangs at night. Yet when Minoru finds himself in a truck accident, his ambitions seemingly come to a sudden end. In his final moments, he laments his powerlessness—no matter how much he trained, there was nothing he could do to overcome his human limitations. But instead of dying, Minoru reawakens as Cid, the second child of the noble Kagenou family, in another world—one where magic is commonplace. With the power he so desired finally within his grasp, he dons the moniker "Shadow" and establishes Shadow Garden: a group whose sole purpose is to combat the enigmatic Cult of Diablos, an organization born from Cid's imagination. However, as Shadow Garden grows in both membership and influence, it becomes increasingly apparent that the Cult of Diablos is not as fictional as Cid had intended.`,
            link: "/anime/48316"
        },
        {
            id: 6,
            name: 'Love Live! School Idol Project',
            portraitImage: 'https://cdn.myanimelist.net/images/anime/11/56849l.jpg',
            landscapeImage: 'https://www.crunchyroll.com/imgsrv/display/thumbnail/1200x675/catalog/crunchyroll/0879534a677ac269a8d6498f6cd23add.jpe',
            synopsis: `Otonokizaka High School is in a crisis! With the number of enrolling students dropping lower and lower every year, the school is set to shut down after its current first years graduate. However, second year Honoka Kousaka refuses to let it go without a fight. Searching for a solution, she comes across popular school idol group A-RISE and sets out to create a school idol group of her own. With the help of her childhood friends Umi Sonoda and Kotori Minami, Honoka forms μ's (pronounced "muse") to boost awareness and popularity of her school. Unfortunately, it's all easier said than done. Student council president Eri Ayase vehemently opposes the establishment of a school idol group and will do anything in her power to prevent its creation. Moreover, Honoka and her friends have trouble attracting any additional members. But the Love Live, a competition to determine the best and most beloved school idol groups in Japan, can help them gain the attention they desperately need. With the contest fast approaching, Honoka must act quickly and diligently to try and bring together a school idol group and win the Love Live in order to save Otonokizaka High School.`,
            link: "/anime/15051"
        },
        {
            id: 7,
            name: 'Another',
            portraitImage: 'https://cdn.myanimelist.net/images/anime/4/75509l.jpg',
            landscapeImage: 'https://www.crunchyroll.com/imgsrv/display/thumbnail/1200x675/catalog/crunchyroll/1f9f9c9be8e2c41b17168a6454f849ff.jpe',
            synopsis: `In class 3-3 of Yomiyama North Junior High, transfer student Kouichi Sakakibara makes his return after taking a sick leave for the first month of school. Among his new classmates, he is inexplicably drawn toward Mei Misaki—a reserved girl with an eyepatch whom he met in the hospital during his absence. But none of his classmates acknowledge her existence; they warn him not to acquaint himself with things that do not exist. Against their words of caution, Kouichi befriends Mei—soon learning of the sinister truth behind his friends' apprehension. The ominous rumors revolve around a former student of the class 3-3. However, no one will share the full details of the grim event with Kouichi. Engrossed in the curse that plagues his class, Kouichi sets out to discover its connection to his new friend. As a series of tragedies arise around them, it is now up to Kouichi, Mei, and their classmates to unravel the eerie mystery—but doing so will come at a hefty price.`,
            link: "/anime/11111"
        },

        {
            id: 8,
            name: 'Danshi Koukousei no Nichijou',
            portraitImage: 'https://cdn.myanimelist.net/images/anime/3/33257l.jpg',
            landscapeImage: 'https://www.crunchyroll.com/imgsrv/display/thumbnail/1200x675/catalog/crunchyroll/068f9d799bd17b21ca875e8591d3d64d.jpe',
            synopsis: "Roaming the halls of the all-boys Sanada North High School are three close comrades: the eccentric ringleader with a hyperactive imagination Hidenori, the passionate Yoshitake, and the rational and prudent Tadakuni. Their lives are filled with giant robots, true love, and intense drama... in their colorful imaginations, at least. In reality, they are just an everyday trio of ordinary guys trying to pass the time, but who said everyday life couldn't be interesting? Whether it's an intricate RPG reenactment or an unexpected romantic encounter on the riverbank at sunset, Danshi Koukousei no Nichijou is rife with bizarre yet hilariously relatable situations that are anything but mundane.",
            link: "/anime/11843"
        },

    ];

    return (
        <div>
            <div className="max-md:hidden">
                <AnimeListKira animeList={animeList} />
            </div>
            <div className="hidden max-md:block mx-2">
                <h1 className='text-2xl font-bold text-color-primary mx-6 my-3'>Anime Favorite Kiratoka</h1>
                <CarouselMobile animeList={animeList} />
            </div>

        </div>
    );
}

export default RandomPage;